spring.datasource.url=jdbc:postgresql://db.owhvhduaujourdbooybbsxzcgxdj.supabase.co:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_DO_SUPABASE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
