spring.datasource.url=jdbc:postgresql://db.owhvhduaujourdbooybbsxzcgxdj.supabase.co:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=joaobatista123@
spring.datasource.hikari.cache-prep-stmts=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=DEBUG
